name: .NET Core

on: 
  push:
    tags: '*'

jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
  
  publish:
    needs: [build]
    name: Publish ArtFactory.Common.DDD to Nuget
    runs-on: [ubuntu-latest]
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: Publish
        run: | 
          version=`git describle --tags`
          dotnet pack src/ArtFactory.Common.DDD -c Release -p:PackageVersion=$version
          dotnet nuget push  src/ArtFactory.Common.DDD/bin/Release/ArtFactory.Common.DDD.$version.nupkg -k ${Nuget_API_KEY} -s https://api.nuget.org/v3/index.json
        env:
          Nuget_API_KEY: ${{secrets.NUGET_API_KEY}}
        
