name: Publish ArtFactory.Common.DDD to Nuget

on: 
  push:
    tags: '*'
jobs: 
  publish: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build and Pack
      run: |
        version=`git describe --tags` 

        dotnet pack -c Release -p:PackageVersion=$version 
        
    - name: Publish packages
      run: |
        version=`git describe --tags` 

        dotnet nuget push ./src/ArtFactory.Common.DDD/bin/Release/ArtFactory.Common.DDD.$version.nupkg -k ${Nuget_API_KEY} -s https://api.nuget.org/v3/index.json

        dotnet nuget push ./src/ArtFactory.Common/bin/Release/ArtFactory.Common.$version.nupkg -k ${Nuget_API_KEY} -s https://api.nuget.org/v3/index.json

      env:
        Nuget_API_KEY: ${{secrets.NUGET_API_KEY}}
        
